"""Coverage tests for src/labclaw/agents/runtime.py.

Import edge case and tool execute return paths.
"""

from __future__ import annotations

from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest

from labclaw.agents.runtime import AgentRuntime
from labclaw.agents.tools import AgentTool, ToolResult

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_llm(*responses: str) -> MagicMock:
    mock = MagicMock()
    mock.complete = AsyncMock(side_effect=list(responses))
    return mock


def _make_tool_returning(name: str, return_value: Any) -> AgentTool:
    """Create an AgentTool whose execute() returns the given value directly."""

    async def fn(**kwargs: Any) -> Any:
        return return_value

    return AgentTool(
        name=name,
        description=f"Tool {name}",
        fn=fn,
        parameters_schema={},
    )


# ---------------------------------------------------------------------------
# Line 44: _uuid() function (used in AgentConfig default_factory)
# ---------------------------------------------------------------------------


class TestUuidFactory:
    def test_uuid_used_in_agent_config(self) -> None:
        """AgentConfig.agent_id is generated by _uuid() — ensures line 44 is covered."""
        from labclaw.agents.runtime import AgentConfig

        cfg = AgentConfig(name="test-agent", system_prompt="You are helpful.")
        assert isinstance(cfg.agent_id, str)
        assert len(cfg.agent_id) == 36

    def test_two_configs_have_different_ids(self) -> None:
        from labclaw.agents.runtime import AgentConfig

        c1 = AgentConfig(name="a", system_prompt="s")
        c2 = AgentConfig(name="b", system_prompt="s")
        assert c1.agent_id != c2.agent_id


# ---------------------------------------------------------------------------
# Lines 261-263: _execute_tool return paths
#   261: result = await tool.execute(**arguments)
#   262: if hasattr(result, "model_dump"):  → ToolResult has model_dump
#   263: return result.model_dump()
#   (implicit) if isinstance(result, dict): → never for ToolResult
#   263: return {"success": True, "data": str(result)}  → non-dict, non-model_dump path
# ---------------------------------------------------------------------------


class TestExecuteToolReturnPaths:
    @pytest.mark.asyncio
    async def test_tool_result_with_model_dump(self) -> None:
        """Lines 259-260: tool.execute() returns ToolResult → .model_dump() is called."""
        rt = AgentRuntime(llm_provider=_make_llm())

        async def fn(**kwargs: Any) -> ToolResult:
            return ToolResult(success=True, data={"value": 42})

        tool = AgentTool(name="t_model", description="d", fn=fn)
        rt.register_tool(tool)

        result = await rt._execute_tool("t_model", {})
        # model_dump() of ToolResult returns a dict
        assert isinstance(result, dict)
        assert result["success"] is True
        assert result["data"] == {"value": 42}

    @pytest.mark.asyncio
    async def test_tool_returning_plain_dict(self) -> None:
        """Lines 261-262: tool.execute() wraps a plain dict in ToolResult, which has model_dump."""
        rt = AgentRuntime(llm_provider=_make_llm())

        # AgentTool.execute() wraps non-ToolResult in ToolResult(success=True, data=...)
        # so the result always has model_dump. We need a result that IS a dict to hit line 262.
        # Directly patch tool.execute to return a plain dict (bypassing AgentTool wrapper).
        async def fn(**kwargs: Any) -> dict:
            return {"key": "value"}

        tool = AgentTool(name="t_dict", description="d", fn=fn)
        rt.register_tool(tool)

        result = await rt._execute_tool("t_dict", {})
        # AgentTool.execute wraps dict in ToolResult, so model_dump path is hit
        assert isinstance(result, dict)
        assert result["success"] is True

    @pytest.mark.asyncio
    async def test_tool_returning_non_dict_non_model(self) -> None:
        """Line 263: tool returns a plain string → wrapped by AgentTool, then model_dump path."""
        rt = AgentRuntime(llm_provider=_make_llm())

        async def fn(**kwargs: Any) -> str:
            return "plain string result"

        tool = AgentTool(name="t_str", description="d", fn=fn)
        rt.register_tool(tool)

        result = await rt._execute_tool("t_str", {})
        # AgentTool wraps string → ToolResult(success=True, data="plain string result")
        # Then model_dump path produces
        # {"success": True, "data": "plain string result", "error": ""}
        assert isinstance(result, dict)
        assert result["success"] is True

    @pytest.mark.asyncio
    async def test_execute_tool_with_model_dump_directly(self) -> None:
        """Force _execute_tool to receive an object with model_dump.

        Bypasses AgentTool wrapping.
        """
        rt = AgentRuntime(llm_provider=_make_llm())

        # Create a mock tool whose execute() returns an object with model_dump
        mock_tool = MagicMock()
        mock_result = MagicMock()
        mock_result.model_dump.return_value = {"custom": "data", "success": True}

        mock_tool.execute = AsyncMock(return_value=mock_result)
        mock_tool.name = "mock_tool"
        rt._tools["mock_tool"] = mock_tool

        result = await rt._execute_tool("mock_tool", {"arg": "val"})
        assert result == {"custom": "data", "success": True}
        mock_result.model_dump.assert_called_once()

    @pytest.mark.asyncio
    async def test_execute_tool_dict_passthrough(self) -> None:
        """Force _execute_tool to receive a plain dict (no model_dump, is dict path)."""
        rt = AgentRuntime(llm_provider=_make_llm())

        mock_tool = MagicMock()
        mock_tool.execute = AsyncMock(return_value={"direct": "dict", "success": True})
        mock_tool.name = "dict_tool"
        # Remove model_dump so hasattr returns False
        del mock_tool.model_dump
        rt._tools["dict_tool"] = mock_tool

        result = await rt._execute_tool("dict_tool", {})
        assert result == {"direct": "dict", "success": True}

    @pytest.mark.asyncio
    async def test_execute_tool_string_fallback(self) -> None:
        """Force _execute_tool to receive a plain string → fallback to str() path (line 263)."""
        rt = AgentRuntime(llm_provider=_make_llm())

        mock_tool = MagicMock()
        mock_tool.execute = AsyncMock(return_value="raw_string")
        mock_tool.name = "str_tool"
        # Remove model_dump so hasattr check fails, and it's not a dict
        del mock_tool.model_dump
        rt._tools["str_tool"] = mock_tool

        result = await rt._execute_tool("str_tool", {})
        # "raw_string" is not a dict and has no model_dump → line 263
        assert result == {"success": True, "data": "raw_string"}


# ---------------------------------------------------------------------------
# Line 44 via module re-import: event registration guard
# ---------------------------------------------------------------------------


class TestEventRegistrationGuard:
    def test_events_already_registered_no_error(self) -> None:
        """Re-importing runtime after events are registered should not raise."""
        from labclaw.core.events import event_registry

        # All three events should already be registered from initial import
        assert event_registry.is_registered("persona.agent.message_received")
        assert event_registry.is_registered("persona.agent.tool_called")
        assert event_registry.is_registered("persona.agent.response_generated")
